# General notebook preparation: Libaries and Datasets

At the beginning, the basic libaries that we work with need to be imported. That includes pandas for data read out, matplot libary for basic plotting, numpy for numeric operations, seaborn for advanced plotting and scipy stats for statistical calculations.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.stats as stats
from pathlib import Path

In [ ]:
ATAC_path_Tgd = Path('data') / 'ATAC_seq_gd_anot.csv'
ATAC_Tgd = pd.read_csv(ATAC_path_Tgd)
ATAC_Tgd.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,MPP4.135+.BM,preT.DN1.Th,...,preT.DN2b.Th,preT.DN3.Th,T.DN4.Th,Tgd.g1.1+d1.24a+.Th,Tgd.g2+d1.24a+.Th,Tgd.g2+d17.24a+.Th,Tgd.Sp,Tgd.g1.1+d1.LN,Tgd.g2+d1.LN,Tgd.g2+d17.LN
0,ImmGenATAC1219.peak_3,chr1,3120109,0.07,10.80,1.0,NaN,NaN,0.11,0.40,...,0.11,0.10,0.35,0.11,0.76,0.53,1.46,0.11,0.12,0.86
1,ImmGenATAC1219.peak_4,chr1,3121485,0.15,3.02,1.0,NaN,NaN,0.11,0.46,...,0.47,0.10,0.58,0.11,0.29,0.53,0.51,0.11,0.70,0.13
2,ImmGenATAC1219.peak_5,chr1,3372787,0.03,1.31,NaN,NaN,NaN,0.11,0.77,...,1.34,1.69,0.34,1.39,1.58,3.16,0.51,0.99,0.12,0.73
3,ImmGenATAC1219.peak_6,chr1,3399217,0.06,2.39,1.0,NaN,NaN,1.58,0.77,...,0.47,1.02,0.10,1.33,0.10,1.48,0.15,0.11,1.26,0.73
4,ImmGenATAC1219.peak_7,chr1,3400115,0.44,2.57,1.0,NaN,NaN,0.11,0.40,...,0.47,0.10,0.58,1.33,1.27,1.11,0.51,2.86,0.70,0.73

In [ ]:
RNA_seq = pd.read_csv('data/mmc2.csv')
RNA_seq = RNA_seq.set_index("Unnamed: 0")  # Gennamen als Index setzen

Tgd_cells = [
    "MPP4.135+.BM",
    "preT.DN1.Th",
    "preT.DN2a.Th",
    "preT.DN2b.Th",
    "preT.DN3.Th",
    "T.DN4.Th",
    "Tgd.g1.1+d1.24a+.Th",
    "Tgd.g2+d1.24a+.Th",
    "Tgd.g2+d17.24a+.Th",
    "Tgd.Sp",
    "Tgd.g1.1+d1.LN",
    "Tgd.g2+d1.LN",
    "Tgd.g2+d17.LN"
]

RNA_Tgd = RNA_seq[Tgd_cells].copy()
RNA_Tgd.head()

,MPP4.135+.BM,preT.DN1.Th,preT.DN2a.Th,preT.DN2b.Th,preT.DN3.Th,T.DN4.Th,Tgd.g1.1+d1.24a+.Th,Tgd.g2+d1.24a+.Th,Tgd.g2+d17.24a+.Th,Tgd.Sp,Tgd.g1.1+d1.LN,Tgd.g2+d1.LN,Tgd.g2+d17.LN
Unnamed: 0,,,,,,,,,,,,,
0610005C13Rik,1.021812,1.022363,1.389747,1.024819,1.024482,1.026430,1.023995,1.167561,1.024819,1.023995,1.025543,1.024819,1.023995
0610007P14Rik,204.298358,162.641117,206.945221,209.187788,198.421365,215.056475,150.742022,174.031477,115.930664,136.200789,108.850425,102.701399,137.925015
0610009B22Rik,76.418169,68.070719,82.468806,89.769337,57.661619,76.399214,47.775227,44.980534,53.461136,42.439750,28.755395,21.517647,29.122837
0610009L18Rik,16.947354,15.450717,13.573968,14.427620,8.249482,1.683173,8.554990,8.781962,29.156630,8.937625,10.815319,10.202163,9.033355
0610009O20Rik,186.261464,160.246297,125.475307,155.928005,120.692893,118.433597,94.062684,113.600798,102.445617,79.315094,84.643541,106.186930,86.383381

In [ ]:
meta_cols = ["TSS", "genes.within.100Kb", "_-log10_bestPvalue", "Included.in.systematic.analysis",
             "ImmGenATAC1219.peakID", "chrom", "Summit", "mm10.60way.phastCons_scores"]
signal_cols_all = [col for col in ATAC_pfiltered.columns 
                   if col not in meta_cols 
                   and col in RNA_seq.columns] #alle Zelltypen Spaltennamen in ATAC, 
#ohne meta_cols und nur, wenn in ATAC, aber als liste und
signal_cols_all

signal_cols_tgd = Tgd_cells

## 2.3 CRE–Gene Association via Correlation

<h3> Linking ATAC-seq peaks (our T-cels gd) to genes via Correlation

Idee: Nur peaks raussuchen, die in 100kb ein Gen haben (Spalte: genes within 100kb). Dann Signalpeak/Genpaare identifizieren. Für ATAC-Datensatz die Signalpeaks über die Zelltypen in einen Vektor packen. Für RNA-Datensatz die Genexpression von dem Gen über die Zelltypen in einen anderen Vektor... Dann Korrelation zwischen Signal peak (ATAC) und Genexpression (RNA)

In [ ]:
ATAC_path_Tgd = Path('data') / 'ATAC_seq_gd_anot.csv'
ATAC_Tgd = pd.read_csv(ATAC_path_Tgd)
ATAC_Tgd.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,MPP4.135+.BM,preT.DN1.Th,...,preT.DN2b.Th,preT.DN3.Th,T.DN4.Th,Tgd.g1.1+d1.24a+.Th,Tgd.g2+d1.24a+.Th,Tgd.g2+d17.24a+.Th,Tgd.Sp,Tgd.g1.1+d1.LN,Tgd.g2+d1.LN,Tgd.g2+d17.LN
0,ImmGenATAC1219.peak_3,chr1,3120109,0.07,10.80,1.0,NaN,NaN,0.11,0.40,...,0.11,0.10,0.35,0.11,0.76,0.53,1.46,0.11,0.12,0.86
1,ImmGenATAC1219.peak_4,chr1,3121485,0.15,3.02,1.0,NaN,NaN,0.11,0.46,...,0.47,0.10,0.58,0.11,0.29,0.53,0.51,0.11,0.70,0.13
2,ImmGenATAC1219.peak_5,chr1,3372787,0.03,1.31,NaN,NaN,NaN,0.11,0.77,...,1.34,1.69,0.34,1.39,1.58,3.16,0.51,0.99,0.12,0.73
3,ImmGenATAC1219.peak_6,chr1,3399217,0.06,2.39,1.0,NaN,NaN,1.58,0.77,...,0.47,1.02,0.10,1.33,0.10,1.48,0.15,0.11,1.26,0.73
4,ImmGenATAC1219.peak_7,chr1,3400115,0.44,2.57,1.0,NaN,NaN,0.11,0.40,...,0.47,0.10,0.58,1.33,1.27,1.11,0.51,2.86,0.70,0.73

In [ ]:
ATAC_Tgd[-(ATAC_Tgd["genes.within.100Kb"].isnull())]

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,MPP4.135+.BM,preT.DN1.Th,...,preT.DN2b.Th,preT.DN3.Th,T.DN4.Th,Tgd.g1.1+d1.24a+.Th,Tgd.g2+d1.24a+.Th,Tgd.g2+d17.24a+.Th,Tgd.Sp,Tgd.g1.1+d1.LN,Tgd.g2+d1.LN,Tgd.g2+d17.LN
11,ImmGenATAC1219.peak_18,chr1,3611363,0.16,3.32,1.0,NaN,Xkr4,0.11,0.11,...,0.87,1.02,0.58,0.40,0.41,0.53,0.51,0.11,1.95,0.73
12,ImmGenATAC1219.peak_19,chr1,3670859,0.76,1.74,1.0,NaN,Xkr4,3.04,4.73,...,2.82,6.59,2.69,1.33,3.82,2.35,1.29,0.99,1.39,3.33
13,ImmGenATAC1219.peak_20,chr1,3671114,0.94,2.02,1.0,NaN,Xkr4,4.84,4.73,...,4.73,5.18,4.47,0.54,2.72,1.48,1.29,0.99,0.68,2.60
14,ImmGenATAC1219.peak_21,chr1,3671437,0.72,2.02,1.0,Xkr4,Xkr4,4.84,2.48,...,3.14,2.29,6.44,0.84,2.69,1.11,4.59,3.12,2.96,0.13
15,ImmGenATAC1219.peak_22,chr1,3671783,0.91,9.67,1.0,NaN,Xkr4,2.58,1.80,...,3.71,3.07,2.76,0.11,2.58,0.97,1.04,2.23,1.33,0.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362325,ImmGenATAC1219.peak_512589,chrY,90811728,0.00,2.33,1.0,NaN,Erdr1,3.49,2.09,...,4.17,7.10,6.93,9.58,9.65,11.37,3.98,15.78,5.85,19.30
362326,ImmGenATAC1219.peak_512590,chrY,90812084,0.00,3.12,1.0,NaN,Erdr1,2.15,1.76,...,2.55,4.00,10.15,6.88,20.55,8.96,2.34,10.00,9.77,10.93
362327,ImmGenATAC1219.peak_512591,chrY,90812450,0.00,3.99,1.0,NaN,Erdr1,2.58,3.32,...,3.37,4.55,8.41,8.61,19.64,8.96,3.61,13.42,14.05,9.01
362328,ImmGenATAC1219.peak_512592,chrY,90812906,0.00,3.21,1.0,NaN,Erdr1,3.04,3.56,...,8.18,10.40,15.50,12.38,15.54,10.92,3.52,11.73,8.31,12.91
362329,ImmGenATAC1219.peak_512595,chrY,90828985,0.00,1.41,NaN,NaN,Erdr1,3.49,1.61,...,1.78,1.02,2.38,3.23,5.39,4.11,4.72,1.62,2.68,1.48

In [ ]:
import scipy.stats as stats
RNA_seq = pd.read_csv('data/mmc2.csv')
RNA_seq.head()

,Unnamed: 0,LTHSC.34-.BM,LTHSC.34+.BM,STHSC.150-.BM,MPP4.135+.BM,proB.CLP.BM,proB.FrA.BM,proB.FrBC.BM,B.FrE.BM,B1b.PC,...,MF.PC,MF.Fem.PC,DC.4+.Sp,DC.8+.Sp,DC.pDC.Sp,FRC.SLN,IAP.SLN,BEC.SLN,LEC.SLN,Ep.MEChi.Th
0,0610005C13Rik,1.096732,1.096732,1.021750,1.021812,1.205236,1.326780,1.392996,1.821243,1.025543,...,1.025785,1.025785,1.251082,1.147249,1.024462,1.019656,1.017884,1.019107,1.017884,1.024720
1,0610007P14Rik,206.053987,246.105317,192.424636,204.298358,189.759175,210.195155,180.219440,137.802543,139.436719,...,121.603448,105.140895,101.841463,175.620707,280.406964,200.228029,208.171821,88.578590,129.021874,140.655763
2,0610009B22Rik,78.272059,78.837030,68.844751,76.418169,106.085619,77.502817,68.213092,57.224426,56.787489,...,88.691426,73.423656,68.881268,60.811907,56.578015,100.397766,37.373080,73.888468,77.191831,84.245816
3,0610009L18Rik,8.577159,16.791386,15.511549,16.947354,10.583704,8.664784,2.878172,8.952120,11.873984,...,6.132818,8.965889,4.080445,11.987408,5.627219,4.227673,2.199352,1.460090,2.482516,1.023995
4,0610009O20Rik,168.645852,157.926022,155.941641,186.261464,162.584556,152.088002,163.072291,133.116083,88.052982,...,102.592399,147.139323,130.924354,107.542142,88.338330,100.779150,86.442408,193.307175,187.212720,45.464889

In [ ]:
RNA_seq = pd.read_csv('data/mmc2.csv')
RNA_seq = RNA_seq.set_index("Unnamed: 0")  # Gennamen als Index setzen

Tgd_cells = [
    "MPP4.135+.BM",
    "preT.DN1.Th",
    "preT.DN2a.Th",
    "preT.DN2b.Th",
    "preT.DN3.Th",
    "T.DN4.Th",
    "Tgd.g1.1+d1.24a+.Th",
    "Tgd.g2+d1.24a+.Th",
    "Tgd.g2+d17.24a+.Th",
    "Tgd.Sp",
    "Tgd.g1.1+d1.LN",
    "Tgd.g2+d1.LN",
    "Tgd.g2+d17.LN"
]

RNA_Tgd = RNA_seq[Tgd_cells].copy()
RNA_Tgd.head()

,MPP4.135+.BM,preT.DN1.Th,preT.DN2a.Th,preT.DN2b.Th,preT.DN3.Th,T.DN4.Th,Tgd.g1.1+d1.24a+.Th,Tgd.g2+d1.24a+.Th,Tgd.g2+d17.24a+.Th,Tgd.Sp,Tgd.g1.1+d1.LN,Tgd.g2+d1.LN,Tgd.g2+d17.LN
Unnamed: 0,,,,,,,,,,,,,
0610005C13Rik,1.021812,1.022363,1.389747,1.024819,1.024482,1.026430,1.023995,1.167561,1.024819,1.023995,1.025543,1.024819,1.023995
0610007P14Rik,204.298358,162.641117,206.945221,209.187788,198.421365,215.056475,150.742022,174.031477,115.930664,136.200789,108.850425,102.701399,137.925015
0610009B22Rik,76.418169,68.070719,82.468806,89.769337,57.661619,76.399214,47.775227,44.980534,53.461136,42.439750,28.755395,21.517647,29.122837
0610009L18Rik,16.947354,15.450717,13.573968,14.427620,8.249482,1.683173,8.554990,8.781962,29.156630,8.937625,10.815319,10.202163,9.033355
0610009O20Rik,186.261464,160.246297,125.475307,155.928005,120.692893,118.433597,94.062684,113.600798,102.445617,79.315094,84.643541,106.186930,86.383381

<b> Korrelations-Analyse von Peak-Gen Paaren bei unseren Tgd-Zellen (13):

signal_cols_tgd = Tgd_cells 

results_corr_tgd = []

for peak_id, row in ATAC_Tgd[ATAC_Tgd["genes.within.100Kb"].notna()].iterrows():
    peak_signal = row[signal_cols_tgd].values.astype(float)
    gene = row["genes.within.100Kb"]

    for gene_name in str(gene).split(","):
        gene_name = gene_name.strip()

        if gene_name in RNA_Tgd.index:
            gene_expr = RNA_Tgd.loc[gene_name, signal_cols_tgd].values.astype(float)
            r, p = stats.pearsonr(peak_signal, gene_expr)

            results_corr_tgd.append({
                "peak_id": row["ImmGenATAC1219.peakID"],
                "gene":    gene_name,
                "r":       r,
                "p_value": p
            })

results_corr_tgd = pd.DataFrame(results_corr_tgd)
results_corr_tgd.to_csv('data/results_corr_tgd.csv', index=False)

In [ ]:
results_corr_tgd = pd.read_csv('data/results_corr_tgd.csv')
results_corr_all= pd.read_csv('data/results_corr_all.csv')

In [ ]:
print(f"\nAnzahl Korrelationen von TGD-Zellen: {len(results_corr_tgd)}")

Anzahl Korrelationen von TGD-Zellen: 933713

In [ ]:
results_corr_tgd.head()

                  peak_id   gene         r   p_value
0  ImmGenATAC1219.peak_41    Rp1 -0.009633  0.975083
1  ImmGenATAC1219.peak_43    Rp1  0.060016  0.845581
2  ImmGenATAC1219.peak_46    Rp1 -0.319756  0.286869
3  ImmGenATAC1219.peak_48    Rp1  0.096712  0.753292
4  ImmGenATAC1219.peak_48  Sox17  0.121571  0.692373

In [ ]:
results_corr_tgd[results_corr_tgd["r"] > 0.7].sort_values("r", ascending=False)

                           peak_id    gene         r       p_value
1979      ImmGenATAC1219.peak_2086   Il17f  0.998686  1.509077e-15
483554  ImmGenATAC1219.peak_274985  Osbpl6  0.998488  3.255187e-15
1959      ImmGenATAC1219.peak_2075   Il17f  0.997891  2.031938e-14
1988      ImmGenATAC1219.peak_2090   Il17f  0.997714  3.162186e-14
338451  ImmGenATAC1219.peak_197929  Abi3bp  0.997449  5.776129e-14
...                            ...     ...       ...           ...
732006  ImmGenATAC1219.peak_415764   Klra3  0.700007  7.721414e-03
84298    ImmGenATAC1219.peak_54750  Mrpl54  0.700006  7.721590e-03
879679  ImmGenATAC1219.peak_481899  C2cd2l  0.700005  7.721652e-03
483160  ImmGenATAC1219.peak_274706  Nfe2l2  0.700001  7.722104e-03
485047  ImmGenATAC1219.peak_276278  Btbd18  0.700000  7.722268e-03

[30925 rows x 4 columns]

In [ ]:
results_corr_tgd[results_corr_tgd["r"] < -0.7].sort_values("r")

                           peak_id           gene         r       p_value
384631  ImmGenATAC1219.peak_216182  1700001C19Rik -0.964467  1.061594e-07
98985    ImmGenATAC1219.peak_65109       B4galnt1 -0.959915  2.041892e-07
147483   ImmGenATAC1219.peak_83984          Fndc8 -0.944267  1.213607e-06
545115  ImmGenATAC1219.peak_311571           Clk2 -0.944156  1.226766e-06
831664  ImmGenATAC1219.peak_460272  D130040H23Rik -0.943434  1.314735e-06
...                            ...            ...       ...           ...
76889    ImmGenATAC1219.peak_53950  E130317F20Rik -0.700046  7.716545e-03
150674   ImmGenATAC1219.peak_85076          Dhx40 -0.700031  7.718468e-03
533041  ImmGenATAC1219.peak_302989          Cetn4 -0.700006  7.721527e-03
760851  ImmGenATAC1219.peak_424697           Tbcb -0.700006  7.721551e-03
541614  ImmGenATAC1219.peak_311068           Prcc -0.700004  7.721809e-03

[6931 rows x 4 columns]

hier habe ich mit der Pearson-Korrelation gearbeitet, da RNA und ATAC seq datensätze beide schon mal log transformiert wurden und quantile normalisiert, und dann zurück linearisiert... Im Yoshida paper benutzen die ebenfalls Pearson. Spearman hat bei annähernd normalverteilten daten eine geringere statistische power, da alles in ränge umgewandelt wird, die wertunterschiede gehen verloren...

<b> Bonferroni- Korrektur

In [ ]:
results_corr_tgd = results_corr_tgd.dropna(subset=['p_value']) #man muss einen NaN Korrelationswert rausnehmen, weil das FDR verwirrt...

In [ ]:
from statsmodels.stats.multitest import multipletests

# Bonferroni-Korrektur anwenden
_, p_bonf, _, _ = multipletests(results_corr_tgd['p_value'], method='bonferroni')
results_corr_tgd['p_bonf'] = p_bonf
#komische Schreibweise, aber multiple sets gibt vier werte zurück und uns interessieren nur die korrgierten p-Werte

# Filtern: nur signifikante Assoziationen behalten
corr_bonf_tgd = results_corr_tgd[results_corr_tgd['p_bonf'] < 0.05]
print(f"Signifikante Assoziationen: {len(corr_bonf_tgd)}")
print(f"Von insgesamt: {len(results_corr_tgd)}")

Signifikante Assoziationen: 303
Von insgesamt: 933712

In [ ]:
corr_bonf_tgd.head() #303 übrig-gebliebende signifikante Werte

                       peak_id    gene         r       p_value        p_bonf
1959  ImmGenATAC1219.peak_2075   Il17f  0.997891  2.031938e-14  1.897245e-08
1979  ImmGenATAC1219.peak_2086   Il17f  0.998686  1.509077e-15  1.409043e-09
1988  ImmGenATAC1219.peak_2090   Il17f  0.997714  3.162186e-14  2.952571e-08
1997  ImmGenATAC1219.peak_2095   Il17f  0.980563  3.966074e-09  3.703171e-03
2543  ImmGenATAC1219.peak_2573  Ogfrl1  0.977710  8.377823e-09  7.822474e-03

<b> FDR-Korrektur (Benjamini-Hochberg)

In [ ]:
_ , p_fdr, _, _ = multipletests(results_corr_tgd['p_value'], method='fdr_bh')
results_corr_tgd['p_fdr'] = p_fdr
corr_fdr_tgd = results_corr_tgd[p_fdr < 0.05]

In [ ]:
corr_fdr_tgd.head() #10248 übrig-gebliebende signifikante Werte

                     peak_id     gene         r   p_value  p_bonf     p_fdr
232  ImmGenATAC1219.peak_229   Npbwr1  0.826966  0.000488     1.0  0.046927
326  ImmGenATAC1219.peak_412   Pcmtd1  0.828240  0.000470     1.0  0.046009
327  ImmGenATAC1219.peak_413   Pcmtd1  0.877619  0.000081     1.0  0.017123
613  ImmGenATAC1219.peak_616     Sgk3  0.867524  0.000122     1.0  0.021803
867  ImmGenATAC1219.peak_716  Arfgef1  0.828007  0.000473     1.0  0.046188

corr_bonf sind alle korrelations pairs, die nach der bonferroni korrektur noch als signfikant übrig bleiben. 

sehr wenige signfikante Werte, weil: wir arbeiten nur mit sehr wenigen Zellen... Alternativ könnte man mit dem gesamten Datensatz arbeiten, aber da könte die Ladedauer ewig sein... Im Yoshida peper haben die für diesen SChritt auch Bonferroni benutzt

Da wir ~933.000 (Peak, Gen)-Paare testen, würden bei α = 0.05 rein zufällig ~46.000 Paare als signifikant erscheinen (multiples Testen). Bonferroni korrigiert das, indem es α durch die Anzahl der Tests teilt (α ≈ 5×10⁻⁸) — bei nur 13 Zelltypen ist diese Schwelle aber kaum erreichbar und verwirft echte Assoziationen. Wir verwenden daher FDR (Benjamini-Hochberg), das in der Genomik Standard ist und mehr statistische Power behält. Bei Bonfe haben wir am Ende nur noch 303 pairs, bei fdr 10248.

<b> Korrelations-Analyse von Peak-Gen Paaren bei allen Zellen (Exkurs):

In [ ]:
meta_cols = ["TSS", "genes.within.100Kb", "_-log10_bestPvalue", "Included.in.systematic.analysis",
             "ImmGenATAC1219.peakID", "chrom", "Summit", "mm10.60way.phastCons_scores"]
signal_cols_all = [col for col in ATAC_pfiltered.columns 
                   if col not in meta_cols 
                   and col in RNA_seq.columns] #alle Zelltypen Spaltennamen in ATAC, 
#ohne meta_cols und nur, wenn in ATAC, aber als liste und
signal_cols_all

['LTHSC.34-.BM',
 'LTHSC.34+.BM',
 'STHSC.150-.BM',
 'MPP4.135+.BM',
 'proB.CLP.BM',
 'proB.FrA.BM',
 'proB.FrBC.BM',
 'B.FrE.BM',
 'B1b.PC',
 'B.T1.Sp',
 'B.T2.Sp',
 'B.T3.Sp',
 'B.Sp',
 'B.Fem.Sp',
 'B.MZ.Sp',
 'B.Fo.Sp',
 'B.mem.Sp',
 'B.GC.CB.Sp',
 'B.GC.CC.Sp',
 'B.PB.Sp',
 'B.PC.Sp',
 'B.PC.BM',
 'preT.DN1.Th',
 'preT.DN2a.Th',
 'preT.DN2b.Th',
 'preT.DN3.Th',
 'T.DN4.Th',
 'T.ISP.Th',
 'T.DP.Th',
 'T.4.Th',
 'T.8.Th',
 'T.4.Nve.Sp',
 'T.4.Nve.Fem.Sp',
 'T.8.Nve.Sp',
 'T.4.Sp.aCD3+CD40.18hr',
 'Treg.4.FP3+.Nrplo.Co',
 'Treg.4.25hi.Sp',
 'T8.TN.P14.Sp',
 'T8.TE.LCMV.d7.Sp',
 'T8.MP.LCMV.d7.Sp',
 'T8.Tcm.LCMV.d180.Sp',
 'T8.Tem.LCMV.d180.Sp',
 'NKT.Sp',
 'NKT.Sp.LPS.3hr',
 'NKT.Sp.LPS.18hr',
 'NKT.Sp.LPS.3d',
 'Tgd.g2+d17.24a+.Th',
 'Tgd.g2+d17.LN',
 'Tgd.g2+d1.24a+.Th',
 'Tgd.g2+d1.LN',
 'Tgd.g1.1+d1.24a+.Th',
 'Tgd.g1.1+d1.LN',
 'Tgd.Sp',
 'NK.27+11b-.BM',
 'NK.27+11b+.BM',
 'NK.27-11b+.BM',
 'NK.27+11b-.Sp',
 'NK.27+11b+.Sp',
 'NK.27-11b+.Sp',
 'ILC2.SI',
 'ILC3.NKp46-CCR6-.SI',
 'ILC3.NKp46+.SI',
 'ILC3.CCR6+.SI',
 'MPP3.48+.BM',
 'GN.BM',
 'GN.Sp',
 'GN.Thio.PC',
 'Mo.6C+II-.Bl',
 'Mo.6C-II-.Bl',
 'MF.pIC.Alv.Lu',
 'MF.226+II+480lo.PC',
 'MF.ICAM+480hi.PC',
 'MF.RP.Sp',
 'MF.Alv.Lu',
 'MF.microglia.CNS',
 'MF.PC',
 'MF.Fem.PC',
 'DC.4+.Sp',
 'DC.8+.Sp',
 'DC.pDC.Sp',
 'FRC.SLN',
 'IAP.SLN',
 'BEC.SLN',
 'LEC.SLN',
 'Ep.MEChi.Th']

results_corr_all = []

for peak_id, row in ATAC_pfiltered[ATAC_pfiltered["genes.within.100Kb"].notna()].iterrows():
    peak_signal = row[signal_cols_all].values.astype(float)
    gene = row["genes.within.100Kb"]

    for gene_name in str(gene).split(","):
        gene_name = gene_name.strip()

        if gene_name in RNA_seq.index:
            gene_expr = RNA_seq.loc[gene_name, signal_cols_all].values.astype(float)
            r, p = stats.pearsonr(peak_signal, gene_expr)

            results_corr_all.append({
                "peak_id": row["ImmGenATAC1219.peakID"],
                "gene":    gene_name,
                "r":       r,
                "p_value": p
            })

results_corr_all = pd.DataFrame(results_corr_all)
results_corr_all.to_csv('data/results_corr_all.csv', index=False)

ich nutze hier die stats korrelations funktion, weil die mir gleich den p-wert berechnet... den brauche ich für die korrekturen. mit dem normalen panda series corr() habe ich nur den r-wert und müsste den p-wert manuell bestimmen

In [ ]:
print(f"\nAnzahl Korrelationen von allen Zellen: {len(results_corr_all)}")

Anzahl Korrelationen von allen Zellen: 933713

In [ ]:
results_corr_all.head()

                  peak_id   gene         r       p_value
0  ImmGenATAC1219.peak_41    Rp1 -0.078288  4.763487e-01
1  ImmGenATAC1219.peak_43    Rp1 -0.131412  2.305944e-01
2  ImmGenATAC1219.peak_46    Rp1  0.373676  4.272850e-04
3  ImmGenATAC1219.peak_48    Rp1  0.803798  2.052007e-20
4  ImmGenATAC1219.peak_48  Sox17  0.022633  8.370992e-01

In [ ]:
results_corr_all[results_corr_all["r"] > 0.7].sort_values("r")

                           peak_id           gene         r       p_value
332448  ImmGenATAC1219.peak_193454          Itgb5  0.700003  9.012261e-14
31935    ImmGenATAC1219.peak_22791         Shisa4  0.700008  9.007129e-14
581111  ImmGenATAC1219.peak_332683  5730488B01Rik  0.700018  8.997207e-14
593063  ImmGenATAC1219.peak_343934          Yipf1  0.700022  8.993124e-14
917778  ImmGenATAC1219.peak_501440           Ccr9  0.700024  8.990992e-14
...                            ...            ...       ...           ...
485282  ImmGenATAC1219.peak_276303       Serping1  0.995585  4.569541e-87
794941  ImmGenATAC1219.peak_441054          Calcb  0.995828  4.380303e-88
41801    ImmGenATAC1219.peak_30580           Ddr2  0.996070  3.683310e-89
196043  ImmGenATAC1219.peak_104763        Clec14a  0.996494  3.267506e-91
900827  ImmGenATAC1219.peak_493985          Paqr9  0.997064  2.086118e-94

[16743 rows x 4 columns]

In [ ]:
len(results_corr_all[results_corr_all["r"] > 0.7].sort_values("r"))

16743

In [ ]:
len(results_corr_tgd[results_corr_tgd["r"] > 0.7].sort_values("r"))

30925

In [ ]:
results_corr_all[results_corr_all["r"] < -0.7].sort_values("r")

                           peak_id     gene         r       p_value
799232  ImmGenATAC1219.peak_444008      Lat -0.733080  1.504707e-15
929593  ImmGenATAC1219.peak_509214      Btk -0.722989  5.581734e-15
874697  ImmGenATAC1219.peak_478534   Vps26b -0.722896  5.648135e-15
702325  ImmGenATAC1219.peak_401472  Eif2ak3 -0.722858  5.675038e-15
132811   ImmGenATAC1219.peak_79952    Trp53 -0.722285  6.102988e-15
682133  ImmGenATAC1219.peak_386810   Rnf216 -0.719037  9.182620e-15
484851  ImmGenATAC1219.peak_276252     Clp1 -0.718876  9.369464e-15
905381  ImmGenATAC1219.peak_496615    Vprbp -0.707943  3.553768e-14
726600  ImmGenATAC1219.peak_413884     Ltbr -0.705403  4.802000e-14

In [ ]:
_ , p_fdr, _, _ = multipletests(results_corr_all['p_value'], method='fdr_bh')
results_corr_all['p_fdr'] = p_fdr
corr_fdr_all = results_corr_all[p_fdr < 0.05]

In [ ]:
len(corr_fdr_all)

188177

In [ ]:
corr_fdr_all.head()

                  peak_id   gene         r       p_value         p_fdr
2  ImmGenATAC1219.peak_46    Rp1  0.373676  4.272850e-04  3.650719e-03
3  ImmGenATAC1219.peak_48    Rp1  0.803798  2.052007e-20  2.529354e-18
7  ImmGenATAC1219.peak_52    Rp1  0.725175  4.222263e-15  2.807964e-13
8  ImmGenATAC1219.peak_52  Sox17  0.422994  5.504399e-05  6.168644e-04
9  ImmGenATAC1219.peak_53    Rp1  0.876096  5.013480e-28  1.352543e-25

Mit mehr Zelltypen als Korrelations-pair basis haben wir zwar weniger werte mit einem korrelationswert r über 0.7, allerdings haben wir viel mehr mit einem stabilen p-wert und somit viel mehr, die den fdr test bestehen. denn bei den 13 zelltypen gibt es mehr schwankungen, also zufällig hohe r werte, die dann aber nicht signifikant sind. die erhöhung der zelltypen als basis macht die r wert robuster und die korrelation aussagekräftiger.