# AllOCRsInfo

In [1]:
import pandas as pd

df = pd.read_csv("../data/ImmGenATAC18_AllOCRsInfo.csv")

In [2]:
df.head()

,ImmGenATAC1219.peakID,chrom,Summit,mm10.60way.phastCons_scores,_-log10_bestPvalue,Included.in.systematic.analysis,TSS,genes.within.100Kb,LTHSC.34-.BM,LTHSC.34+.BM,...,DC.4+.Sp,DC.8+.Sp,DC.pDC.Sp,DC.103+11b+.SI,DC.103+11b-.SI,FRC.SLN,IAP.SLN,BEC.SLN,LEC.SLN,Ep.MEChi.Th
0,ImmGenATAC1219.peak_1,chr1,3020786,0.00,0.56,NaN,NaN,NaN,0.41,0.71,...,0.10,0.10,3.19,1.37,0.52,1.27,0.10,0.57,3.27,1.41
1,ImmGenATAC1219.peak_2,chr1,3087226,0.00,0.50,NaN,NaN,NaN,0.41,1.64,...,1.70,0.10,1.41,0.47,0.11,0.92,0.98,2.16,2.34,0.94
2,ImmGenATAC1219.peak_3,chr1,3120109,0.07,10.80,1.0,NaN,NaN,2.36,0.10,...,0.87,0.54,2.72,0.95,0.11,63.38,8.92,1.33,1.04,0.11
3,ImmGenATAC1219.peak_4,chr1,3121485,0.15,3.02,1.0,NaN,NaN,0.41,0.10,...,0.44,1.83,0.66,0.11,0.92,13.50,0.98,1.28,1.04,0.11
4,ImmGenATAC1219.peak_5,chr1,3372787,0.03,1.31,NaN,NaN,NaN,0.41,0.10,...,0.44,0.10,0.66,1.79,0.51,0.92,0.75,1.33,1.61,4.50

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 512595 entries, 0 to 512594
Data columns (total 98 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   ImmGenATAC1219.peakID            512595 non-null  str
 1   chrom                            512595 non-null  str
 2   Summit                           512595 non-null  int64
 3   mm10.60way.phastCons_scores      512595 non-null  float64
 4   _-log10_bestPvalue               512595 non-null  float64
 5   Included.in.systematic.analysis  334879 non-null  float64
 6   TSS                              14292 non-null   str
 7   genes.within.100Kb               427710 non-null  str
 8   LTHSC.34-.BM                     512595 non-null  float64
 9   LTHSC.34+.BM                     512595 non-null  float64
 10  STHSC.150-.BM                    512595 non-null  float64
 11  MPP4.135+.BM                     512595 non-null  float64
 12  proB.CLP.BM                      512595 non-null  float64
 13  proB.FrA.BM                      512595 non-null  float64
 14  proB.FrBC.BM                     512595 non-null  float64
 15  preB.FrD.BM                      512595 non-null  float64
 16  B.FrE.BM                         512595 non-null  float64
 17  B1b.PC                           512595 non-null  float64
 18  B.T1.Sp                          512595 non-null  float64
 19  B.T2.Sp                          512595 non-null  float64
 20  B.T3.Sp                          512595 non-null  float64
 21  B.Sp                             512595 non-null  float64
 22  B.Fem.Sp                         512595 non-null  float64
 23  B.MZ.Sp                          512595 non-null  float64
 24  B.Fo.Sp                          512595 non-null  float64
 25  B.mem.Sp                         512595 non-null  float64
 26  B.GC.CB.Sp                       512595 non-null  float64
 27  B.GC.CC.Sp                       512595 non-null  float64
 28  B.PB.Sp                          512595 non-null  float64
 29  B.PC.Sp                          512595 non-null  float64
 30  B.PC.BM                          512595 non-null  float64
 31  preT.DN1.Th                      512595 non-null  float64
 32  preT.DN2a.Th                     512595 non-null  float64
 33  preT.DN2b.Th                     512595 non-null  float64
 34  preT.DN3.Th                      512595 non-null  float64
 35  T.DN4.Th                         512595 non-null  float64
 36  T.ISP.Th                         512595 non-null  float64
 37  T.DP.Th                          512595 non-null  float64
 38  T.4.Th                           512595 non-null  float64
 39  T.8.Th                           512595 non-null  float64
 40  T.4.Nve.Sp                       512595 non-null  float64
 41  T.4.Nve.Fem.Sp                   512595 non-null  float64
 42  T.8.Nve.Sp                       512595 non-null  float64
 43  T.4.Sp.aCD3+CD40.18hr            512595 non-null  float64
 44  Treg.4.FP3+.Nrplo.Co             512595 non-null  float64
 45  Treg.4.25hi.Sp                   512595 non-null  float64
 46  T8.TN.P14.Sp                     512595 non-null  float64
 47  T8.IEL.LCMV.d7.SI                512595 non-null  float64
 48  T8.TE.LCMV.d7.Sp                 512595 non-null  float64
 49  T8.MP.LCMV.d7.Sp                 512595 non-null  float64
 50  T8.Tcm.LCMV.d180.Sp              512595 non-null  float64
 51  T8.Tem.LCMV.d180.Sp              512595 non-null  float64
 52  NKT.Sp                           512595 non-null  float64
 53  NKT.Sp.LPS.3hr                   512595 non-null  float64
 54  NKT.Sp.LPS.18hr                  512595 non-null  float64
 55  NKT.Sp.LPS.3d                    512595 non-null  float64
 56  Tgd.g2+d17.24a+.Th               512595 non-null  float64
 57  Tgd.g2+d17.LN                    512595 non-null  float64
 58  Tgd.g2+d1.24a+.Th                512595 non-null  float64
 59  Tgd.g2+d1.LN                     512595 non-null  float64
 60  Tgd.g1.1+d1.24a+.Th              512595 non-null  float64
 61  Tgd.g1.1+d1.LN                   512595 non-null  float64
 62  Tgd.Sp                           512595 non-null  float64
 63  NK.27+11b-.BM                    512595 non-null  float64
 64  NK.27+11b+.BM                    512595 non-null  float64
 65  NK.27-11b+.BM                    512595 non-null  float64
 66  NK.27+11b-.Sp                    512595 non-null  float64
 67  NK.27+11b+.Sp                    512595 non-null  float64
 68  NK.27-11b+.Sp                    512595 non-null  float64
 69  ILC2.SI                          512595 non-null  float64
 70  ILC3.NKp46-CCR6-.SI              512595 non-null  float64
 71  ILC3.NKp46+.SI                   512595 non-null  float64
 72  ILC3.CCR6+.SI                    512595 non-null  float64
 73  MPP3.48+.BM                      512595 non-null  float64
 74  GN.BM                            512595 non-null  float64
 75  GN.Sp                            512595 non-null  float64
 76  GN.Thio.PC                       512595 non-null  float64
 77  Mo.6C+II-.Bl                     512595 non-null  float64
 78  Mo.6C-II-.Bl                     512595 non-null  float64
 79  MF.pIC.Alv.Lu                    512595 non-null  float64
 80  MF.226+II+480lo.PC               512595 non-null  float64
 81  MF.ICAM+480hi.PC                 512595 non-null  float64
 82  MF.RP.Sp                         512595 non-null  float64
 83  MF.LP.SI                         512595 non-null  float64
 84  MF.Alv.Lu                        512595 non-null  float64
 85  MF.microglia.CNS                 512595 non-null  float64
 86  MF.PC                            512595 non-null  float64
 87  MF.Fem.PC                        512595 non-null  float64
 88  DC.4+.Sp                         512595 non-null  float64
 89  DC.8+.Sp                         512595 non-null  float64
 90  DC.pDC.Sp                        512595 non-null  float64
 91  DC.103+11b+.SI                   512595 non-null  float64
 92  DC.103+11b-.SI                   512595 non-null  float64
 93  FRC.SLN                          512595 non-null  float64
 94  IAP.SLN                          512595 non-null  float64
 95  BEC.SLN                          512595 non-null  float64
 96  LEC.SLN                          512595 non-null  float64
 97  Ep.MEChi.Th                      512595 non-null  float64
dtypes: float64(93), int64(1), str(4)
memory usage: 383.3 MB

# mmc1

QC metrics for ATAC-seq samples  
Summary of immune cell populations and sequencing QC statistics

Source: Yoshida et. al. cis-Regulatory Atlas of Mouse Immune System

In [ ]:
mmc1 = pd.read_excel("../data/mmc1.xlsx")
## im terminal: uv add openpyxl

In [15]:
mmc1.head()

,SampleName,CellType,ImmGenLab,Lineage,CellFamily,Organ,SortingMarkers,InputCellNumber,PF.reads,%chrM.mapped,Paired.read.after.removing.PCR.duplication,%fragment.1Kb_TSS,Replicate.cor
0,LTHSC.34-.BM#1,LTHSC.34-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34-,677,22287984,4.58,2470102,10.60,NaN
1,LTHSC.34+.BM#1,LTHSC.34+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150+CD48-CD34+,2483,28588536,3.17,7675501,7.70,NaN
2,STHSC.150-.BM#1,STHSC.150-.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135-CD150-CD48-,3660,22170346,3.25,6060045,11.13,NaN
3,MPP4.135+.BM#1,MPP4.135+.BM,Wagers,Stem&Prog,Stem&Prog Cell,Bone Marrow,Lin-Sca1+ckit+CD135+,10000,24003590,13.83,6128252,18.96,NaN
4,proB.CLP.BM#1,proB.CLP.BM,Hardy,B,B Cell,Bone Marrow,CD19-IgM-CD43+CD24-CD45R-CD93+CD117+IL7Ra+PI-D...,10000,23578208,7.67,6588564,13.21,0.868

In [16]:
mmc1.info()

<class 'pandas.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   SampleName                                  181 non-null    str
 1   CellType                                    181 non-null    str
 2   ImmGenLab                                   181 non-null    str
 3   Lineage                                     181 non-null    str
 4   CellFamily                                  181 non-null    str
 5   Organ                                       181 non-null    str
 6   SortingMarkers                              181 non-null    str
 7   InputCellNumber                             181 non-null    int64
 8   PF.reads                                    181 non-null    int64
 9   %chrM.mapped                                181 non-null    float64
 10  Paired.read.after.removing.PCR.duplication  181 non-null    int64
 11  %fragment.1Kb_TSS                           181 non-null    float64
 12  Replicate.cor                               176 non-null    float64
dtypes: float64(3), int64(3), str(7)
memory usage: 18.5 KB

# mmc2

In [ ]:
mmc2 = pd.read_csv("../data/mmc2.csv")

In [18]:
mmc2.head()

,Unnamed: 0,LTHSC.34-.BM,LTHSC.34+.BM,STHSC.150-.BM,MPP4.135+.BM,proB.CLP.BM,proB.FrA.BM,proB.FrBC.BM,B.FrE.BM,B1b.PC,...,MF.PC,MF.Fem.PC,DC.4+.Sp,DC.8+.Sp,DC.pDC.Sp,FRC.SLN,IAP.SLN,BEC.SLN,LEC.SLN,Ep.MEChi.Th
0,0610005C13Rik,1.096732,1.096732,1.021750,1.021812,1.205236,1.326780,1.392996,1.821243,1.025543,...,1.025785,1.025785,1.251082,1.147249,1.024462,1.019656,1.017884,1.019107,1.017884,1.024720
1,0610007P14Rik,206.053987,246.105317,192.424636,204.298358,189.759175,210.195155,180.219440,137.802543,139.436719,...,121.603448,105.140895,101.841463,175.620707,280.406964,200.228029,208.171821,88.578590,129.021874,140.655763
2,0610009B22Rik,78.272059,78.837030,68.844751,76.418169,106.085619,77.502817,68.213092,57.224426,56.787489,...,88.691426,73.423656,68.881268,60.811907,56.578015,100.397766,37.373080,73.888468,77.191831,84.245816
3,0610009L18Rik,8.577159,16.791386,15.511549,16.947354,10.583704,8.664784,2.878172,8.952120,11.873984,...,6.132818,8.965889,4.080445,11.987408,5.627219,4.227673,2.199352,1.460090,2.482516,1.023995
4,0610009O20Rik,168.645852,157.926022,155.941641,186.261464,162.584556,152.088002,163.072291,133.116083,88.052982,...,102.592399,147.139323,130.924354,107.542142,88.338330,100.779150,86.442408,193.307175,187.212720,45.464889

In [23]:
mmc2.info()

<class 'pandas.DataFrame'>
RangeIndex: 17535 entries, 0 to 17534
Data columns (total 87 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             17535 non-null  str
 1   LTHSC.34-.BM           17535 non-null  float64
 2   LTHSC.34+.BM           17535 non-null  float64
 3   STHSC.150-.BM          17535 non-null  float64
 4   MPP4.135+.BM           17535 non-null  float64
 5   proB.CLP.BM            17535 non-null  float64
 6   proB.FrA.BM            17535 non-null  float64
 7   proB.FrBC.BM           17535 non-null  float64
 8   B.FrE.BM               17535 non-null  float64
 9   B1b.PC                 17535 non-null  float64
 10  B.T1.Sp                17535 non-null  float64
 11  B.T2.Sp                17535 non-null  float64
 12  B.T3.Sp                17535 non-null  float64
 13  B.Sp                   17535 non-null  float64
 14  B.Fem.Sp               17535 non-null  float64
 15  B.MZ.Sp                17535 non-null  float64
 16  B.Fo.Sp                17535 non-null  float64
 17  B.mem.Sp               17535 non-null  float64
 18  B.GC.CB.Sp             17535 non-null  float64
 19  B.GC.CC.Sp             17535 non-null  float64
 20  B.PB.Sp                17535 non-null  float64
 21  B.PC.Sp                17535 non-null  float64
 22  B.PC.BM                17535 non-null  float64
 23  preT.DN1.Th            17535 non-null  float64
 24  preT.DN2a.Th           17535 non-null  float64
 25  preT.DN2b.Th           17535 non-null  float64
 26  preT.DN3.Th            17535 non-null  float64
 27  T.DN4.Th               17535 non-null  float64
 28  T.ISP.Th               17535 non-null  float64
 29  T.DP.Th                17535 non-null  float64
 30  T.4.Th                 17535 non-null  float64
 31  T.8.Th                 17535 non-null  float64
 32  T.4.Nve.Sp             17535 non-null  float64
 33  T.4.Nve.Fem.Sp         17535 non-null  float64
 34  T.8.Nve.Sp             17535 non-null  float64
 35  T.4.Sp.aCD3+CD40.18hr  17535 non-null  float64
 36  Treg.4.FP3+.Nrplo.Co   17535 non-null  float64
 37  Treg.4.25hi.Sp         17535 non-null  float64
 38  T8.TN.P14.Sp           17535 non-null  float64
 39  T8.IEL.LCMV.d7.Gut     17535 non-null  float64
 40  T8.TE.LCMV.d7.Sp       17535 non-null  float64
 41  T8.MP.LCMV.d7.Sp       17535 non-null  float64
 42  T8.Tcm.LCMV.d180.Sp    17535 non-null  float64
 43  T8.Tem.LCMV.d180.Sp    17535 non-null  float64
 44  NKT.Sp                 17535 non-null  float64
 45  NKT.Sp.LPS.3hr         17535 non-null  float64
 46  NKT.Sp.LPS.18hr        17535 non-null  float64
 47  NKT.Sp.LPS.3d          17535 non-null  float64
 48  Tgd.g2+d17.24a+.Th     17535 non-null  float64
 49  Tgd.g2+d17.LN          17535 non-null  float64
 50  Tgd.g2+d1.24a+.Th      17535 non-null  float64
 51  Tgd.g2+d1.LN           17535 non-null  float64
 52  Tgd.g1.1+d1.24a+.Th    17535 non-null  float64
 53  Tgd.g1.1+d1.LN         17535 non-null  float64
 54  Tgd.Sp                 17535 non-null  float64
 55  NK.27+11b-.BM          17535 non-null  float64
 56  NK.27+11b+.BM          17535 non-null  float64
 57  NK.27-11b+.BM          17535 non-null  float64
 58  NK.27+11b-.Sp          17535 non-null  float64
 59  NK.27+11b+.Sp          17535 non-null  float64
 60  NK.27-11b+.Sp          17535 non-null  float64
 61  ILC2.SI                17535 non-null  float64
 62  ILC3.NKp46-CCR6-.SI    17535 non-null  float64
 63  ILC3.NKp46+.SI         17535 non-null  float64
 64  ILC3.CCR6+.SI          17535 non-null  float64
 65  MPP3.48+.BM            17535 non-null  float64
 66  GN.BM                  17535 non-null  float64
 67  GN.Sp                  17535 non-null  float64
 68  GN.Thio.PC             17535 non-null  float64
 69  Mo.6C+II-.Bl           17535 non-null  float64
 70  Mo.6C-II-.Bl           17535 non-null  float64
 71  MF.pIC.Alv.Lu          17535 non-null  float64
 72  MF.226+II+480lo.PC     17535 non-null  float64
 73  MF.ICAM+480hi.PC       17535 non-null  float64
 74  MF.RP.Sp               17535 non-null  float64
 75  MF.Alv.Lu              17535 non-null  float64
 76  MF.microglia.CNS       17535 non-null  float64
 77  MF.PC                  17535 non-null  float64
 78  MF.Fem.PC              17535 non-null  float64
 79  DC.4+.Sp               17535 non-null  float64
 80  DC.8+.Sp               17535 non-null  float64
 81  DC.pDC.Sp              17535 non-null  float64
 82  FRC.SLN                17535 non-null  float64
 83  IAP.SLN                17535 non-null  float64
 84  BEC.SLN                17535 non-null  float64
 85  LEC.SLN                17535 non-null  float64
 86  Ep.MEChi.Th            17535 non-null  float64
dtypes: float64(86), str(1)
memory usage: 11.6 MB

In [24]:
mmc2.index[:10]

RangeIndex(start=0, stop=10, step=1)

# Gene annotations (refFlat)

In [ ]:
#considering the note on the github --> giving order to the txt file
cols = [
    "gene_name",
    "transcript_name",
    "chrom",
    "strand",
    "txStart",
    "txEnd",
    "cdsStart",
    "cdsEnd",
    "exonCount",
    "exonStarts",
    "exonEnds"
]

refFlat = pd.read_csv("../data/Gene annotations.txt", sep="\t", names=cols)
# need to tell pandas that the txt is tab seperated

In [30]:
refFlat.head()

,gene_name,transcript_name,chrom,strand,txStart,txEnd,cdsStart,cdsEnd,exonCount,exonStarts,exonEnds
0,Wdsub1,NM_001159636,chr2,-,59855193,59882606,59855270,59878527,11,"59855193,59858609,59861560,59862619,59862816,5...","59855275,59858750,59861737,59862726,59862857,5..."
1,Rbm18,NM_001159635,chr2,-,36116078,36136704,36117814,36134247,6,"36116078,36120812,36122851,36127214,36134134,3...","36117974,36120898,36122938,36127251,36134263,3..."
2,Prrc2b,NM_001159634,chr2,+,32151147,32234537,32182511,32230742,32,"32151147,32182457,32183122,32185344,32187480,3...","32151291,32182626,32183300,32185447,32187553,3..."
3,Ildr2,NM_001164528,chr1,+,166254138,166316832,166254375,166310795,10,"166254138,166269304,166270498,166291415,166294...","166254466,166269637,166270618,166291472,166294..."
4,Perm1,NM_172417,chr4,+,156215926,156221307,156217000,156220222,4,"156215926,156216716,156219740,156220109,","156215975,156219185,156219866,156221307,"

In [31]:
refFlat.info()

<class 'pandas.DataFrame'>
RangeIndex: 47382 entries, 0 to 47381
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gene_name        47382 non-null  str
 1   transcript_name  47382 non-null  str
 2   chrom            47382 non-null  str
 3   strand           47382 non-null  str
 4   txStart          47382 non-null  int64
 5   txEnd            47382 non-null  int64
 6   cdsStart         47382 non-null  int64
 7   cdsEnd           47382 non-null  int64
 8   exonCount        47382 non-null  int64
 9   exonStarts       47382 non-null  str
 10  exonEnds         47382 non-null  str
dtypes: int64(5), str(6)
memory usage: 4.0 MB

In [32]:
(refFlat["chrom"] == "chr1").sum()

np.int64(2545)